"""Real OpenAI GPT provider (Q2). Explicit timeout; caller falls back to fixture on error."""
from __future__ import annotations

from .base import ExecutionProvider, ExecutionResult, TaskExecutionContext
from .fixture import _ROLE_FILE, _slug


class OpenAIExecutionProvider(ExecutionProvider):
    name = "openai"

    def __init__(self, api_key: str, model: str, timeout: float):
        self.model = model
        self.timeout = timeout
        # Imported lazily so the package is optional in demo mode.
        from openai import OpenAI

        self._client = OpenAI(api_key=api_key, timeout=timeout)

    def execute_task(self, ctx: TaskExecutionContext) -> ExecutionResult:
        path_tmpl, _ext = _ROLE_FILE.get(ctx.role_code, ("src/{slug}.txt", "txt"))
        code_path = path_tmpl.format(slug=_slug(ctx.task_title))
        prompt = (
            f"You are the {ctx.role_code} agent on a software project. "
            f"Produce the file content for task '{ctx.task_title}'. "
            f"Description: {ctx.description or '(none)'}. Return only the file body."
        )
        resp = self._client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            timeout=self.timeout,
        )
        content = resp.choices[0].message.content or ""
        usage = getattr(resp, "usage", None)
        metrics = {}
        if usage is not None:
            metrics = {
                "input": getattr(usage, "prompt_tokens", None),
                "output": getattr(usage, "completion_tokens", None),
                "total": getattr(usage, "total_tokens", None),
            }
        changes = [
            {"path": code_path, "operation": "create", "content": content},
            {"path": f".ai-dlc/tasks/{ctx.task_id}.md",
             "operation": "create",
             "content": f"# Task Result — {ctx.task_title}\n\nGenerated by OpenAI ({self.model})."},
        ]
        return ExecutionResult(
            changes=changes, artifact_summary=f"OpenAI-generated {len(changes)} files.",
            token_metrics=metrics, execution_mode="AI_AGENT", demo=False,
        )
